repos:

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/pylint
  rev: v2.14.5
  hooks:
  - id: pylint
    additional_dependencies: [toml]
    verbose: true
