#!/usr/bin/env python3
import asyncio
import sys

from PyQt5.QtWidgets import QApplication, QMainWindow
from qasync import QEventLoop

from bubblesub.ui.vim_text_edit import VimTextEdit


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        text_edit = VimTextEdit(self)
        text_edit.vim_mode_enabled = True
        self.setCentralWidget(text_edit)


def main():

    app = QApplication(sys.argv)
    app.setApplicationName("bubblesub vim playground")
    loop = QEventLoop(app)
    asyncio.set_event_loop(loop)
    # asyncio.events._set_running_loop(loop)

    with loop:
        window = MainWindow()
        window.show()

        loop.run_forever()


if __name__ == "__main__":
    main()
