name: bubblesub

on: [push]

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update packages
      run: sudo apt-get update
    - name: Install Python3 packages
      run: sudo apt-get install python3-setuptools python3-wheel
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run precommit
      run: SKIP=pylint pre-commit run -a

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: docker build -t bubblesub .
    - name: Run image
      run: docker run --env DISPLAY=':99.0' -t bubblesub
